Bem
SHTbIK37/profile pull request #3
Opened 2022-06-04 09:10 UTC by SHTbIK37

2022-06-05 09:09 UTC, shtbik requested changes

2022-06-05 09:09 UTC, shtbik commented on index.html
> +        <img src="/assets/image 11.png" alt="Стена" />
Don't use names with spaces

2022-06-05 09:09 UTC, shtbik commented on index.html
> +    <title>Document</title>
Add real title and description

2022-06-05 09:09 UTC, shtbik commented on index.html
> +            alt="Фото 4х3"
Use english

2022-06-05 09:09 UTC, shtbik commented on index.html
> +              href="https://github.com/SHTbIK37"
Add `target="_blank"` attribute to open the link in a new tab. Better to do it for all external links

2022-06-05 09:09 UTC, shtbik commented on index.html
> +    <!-- <script src="./js/script.js"></script> -->
Remove

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +  align-items: center;
Is it necessary?

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +.links {
Cool 👍🏼

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +  padding: 13px 32px 13px 32px;
You can use short standard:
`padding: 13px 32px`

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +  font-size: 18px;
Remind me to tell you about a different types of dimensions - `px/rem/em`

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +  height: 300px;
Are you sure that you need it?

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +  width: 67%;
Check this block on the mobile view. If you use `width` in percentage, it's worth adding `min-width`.

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +  width: 495px;
This looks not flexible. What will happen on the mobile?

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +  margin-top: 150px;
Replace above two lines with:
`margin: 150px 328px 0;`

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +  font-weight: 400;
This should be by default. You also can use the alias "normal"

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +
Can remove this line

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +.careers__year {
👍🏼

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +  #prlinkimg {
I think it's something old

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +@media only screen and (min-width: 250px) and (max-width: 550px) {
You can remove `(min-width: 250px)`

2022-06-05 09:09 UTC, shtbik commented on styles/styles.css
> +@media only screen and (min-width: 769px) and (max-width: 1280px) {
The idea is to accumulate styles when you get down so you don't need to to write the same styles every breakpoint. To make it you don't need restrict it from both sides (max-width and min-width), use max-width only:
default styles -> (max-width: 1280px) (and less) -> (max-width: 768px) (includes styles from previous 1280px and less) -> (max-width: 550px) (and so on) -> and less.

Look at this to get an idea
https://habr.com/ru/post/269419/

Don't need to change it this time but good to know for the future.

2022-06-05 09:09 UTC, shtbik commented on index.html
>  <html lang="en">
Use https://validator.w3.org/#validate_by_upload to check correctness of your HTML

2022-06-07 10:12 UTC, shtbik1 commented on index.html
> +        <img src="/assets/image 11.png" alt="Стена" />
done

2022-06-07 10:13 UTC, SHTbIK37 commented on index.html
> +    <title>Document</title>
done

2022-06-07 10:13 UTC, SHTbIK37 commented on index.html
> +            alt="Фото 4х3"
done

2022-06-07 14:20 UTC, SHTbIK37 commented on index.html
> +              href="https://github.com/SHTbIK37"
done

2022-06-07 14:20 UTC, shtbik1 commented on index.html
> +    <!-- <script src="./js/script.js"></script> -->
done

2022-06-07 14:20 UTC, SHTbIK37 commented on styles/styles.css
> +  font-size: 18px;
done

2022-06-07 14:36 UTC, shtbik1 commented on styles/styles.css
> +  height: 300px;
yes

2022-06-07 14:36 UTC, shtbik1 commented on styles/styles.css
> +  width: 67%;
on mobile looks good

2022-06-07 14:37 UTC, SHTbIK37 commented on styles/styles.css
> +  width: 495px;
for different resolution i use different width

2022-06-07 14:38 UTC, shtbik1 commented on styles/styles.css
> +  margin-top: 150px;
done

2022-06-07 14:38 UTC, SHTbIK37 commented on styles/styles.css
> +  font-weight: 400;
ok

2022-06-07 14:39 UTC, SHTbIK37 commented on styles/styles.css
> +  #prlinkimg {
done

2022-06-07 14:39 UTC, shtbik1 commented on index.html
>  <html lang="en">
pass

2022-06-07 14:40 UTC, shtbik1 commented on styles/styles.css
> +  align-items: center;
yes

2022-06-07 14:41 UTC, SHTbIK37 commented on styles/styles.css
> +  padding: 13px 32px 13px 32px;
done

2022-06-07 14:41 UTC, shtbik1 commented on styles/styles.css
> +@media only screen and (min-width: 250px) and (max-width: 550px) {
done

2022-06-09 10:09 UTC, shtbik commented
Review responsive design again and try to make it better:

<img width="321" alt="Снимок экрана 2022-06-09 в 8 05 43 PM" src="https://user-images.githubusercontent.com/12717213/172822711-fb975979-f28a-4037-919e-0544a8a0df00.png">
<img width="537" alt="Снимок экрана 2022-06-09 в 8 06 33 PM" src="https://user-images.githubusercontent.com/12717213/172822715-c7beea45-9ceb-4dda-a334-5b76870185c9.png">
<img width="1341" alt="Снимок экрана 2022-06-09 в 8 04 22 PM" src="https://user-images.githubusercontent.com/12717213/172822680-7318143b-a736-4ba0-8ef7-84b1ce09954c.png">
<img width="888" alt="Снимок экрана 2022-06-09 в 8 04 00 PM" src="https://user-images.githubusercontent.com/12717213/172822697-fe8c3318-c97a-49f3-88f4-27c1d0e189d9.png">
<img width="826" alt="Снимок экрана 2022-06-09 в 8 04 49 PM" src="https://user-images.githubusercontent.com/12717213/172822707-898ab699-843b-42bb-829e-3c0b601ef2b5.png">
<img width="449" alt="Снимок экрана 2022-06-09 в 8 05 38 PM" src="https://user-images.githubusercontent.com/12717213/172822710-174aa52f-6348-414c-88e7-014e86d61c54.png">

2022-06-21 10:11 UTC, shtbik approved these changes
g2g

2022-06-21 10:14 UTC, merged